"""add alert acknowledge and snooze fields

Revision ID: 286dc60b45e2
Revises: cd18826d4fd9
Create Date: 2026-08-21 13:20:40.764933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286dc60b45e2'
down_revision: Union[str, None] = 'cd18826d4fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('acknowledged_by', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('snoozed_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'snoozed_until')
    op.drop_column('alerts', 'acknowledged_by')
    op.drop_column('alerts', 'acknowledged_at')
    # ### end Alembic commands ###
