"""baseline schema

Revision ID: 65f7b8e330e3
Revises: 
Create Date: 2026-08-19 11:45:39.959957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f7b8e330e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('actor_email', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vms',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('environment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('agent_token_hash', sa.String(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('mem_percent', sa.Float(), nullable=True),
    sa.Column('disk_percent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('containers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('vm_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('mem_usage', sa.String(), nullable=True),
    sa.Column('restart_count', sa.Integer(), nullable=True),
    sa.Column('ports', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vm_id'], ['vms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_sources',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('vm_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vm_id'], ['vms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('vm_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sub_state', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vm_id'], ['vms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_vm_access',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('vm_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vm_id'], ['vms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vm_id', name='uq_user_vm')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_vm_access')
    op.drop_table('services')
    op.drop_table('log_sources')
    op.drop_table('containers')
    op.drop_table('vms')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('environments')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
