"""add metric_samples table

Revision ID: 84496962add1
Revises: 286dc60b45e2
Create Date: 2026-08-21 13:51:21.562586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84496962add1'
down_revision: Union[str, None] = '286dc60b45e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_samples',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('vm_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('mem_percent', sa.Float(), nullable=True),
    sa.Column('disk_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['vm_id'], ['vms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_samples_recorded_at'), 'metric_samples', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_metric_samples_vm_id'), 'metric_samples', ['vm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_samples_vm_id'), table_name='metric_samples')
    op.drop_index(op.f('ix_metric_samples_recorded_at'), table_name='metric_samples')
    op.drop_table('metric_samples')
    # ### end Alembic commands ###
