"""add is_custom to services

Revision ID: acbde94af839
Revises: f4b704f5e61a
Create Date: 2026-08-19 16:03:36.373198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acbde94af839'
down_revision: Union[str, None] = 'f4b704f5e61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('is_custom', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'is_custom')
    # ### end Alembic commands ###
