"""add alerts table

Revision ID: cd18826d4fd9
Revises: 4e95b00ce6a2
Create Date: 2026-08-20 04:25:45.146636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd18826d4fd9'
down_revision: Union[str, None] = '4e95b00ce6a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('vm_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_name', sa.String(), nullable=False),
    sa.Column('rule', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vm_id'], ['vms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vm_id', 'resource_type', 'resource_name', 'rule', name='uq_alert_identity')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    # ### end Alembic commands ###
