"""add resource settings table

Revision ID: f4b704f5e61a
Revises: 65f7b8e330e3
Create Date: 2026-08-19 13:17:48.760010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b704f5e61a'
down_revision: Union[str, None] = '65f7b8e330e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_settings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('vm_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('monitor_enabled', sa.Boolean(), nullable=False),
    sa.Column('logs_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vm_id'], ['vms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vm_id', 'resource_type', 'name', name='uq_resource_setting')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_settings')
    # ### end Alembic commands ###
